database:
  connectionUri: "MONGODB_API_URI"

server:
  port: PORT

staticfile:
  dir: "DIR_FILE"
  maxUploadSize: MAX_FILE_SIZE(KB)

gcloud:
  projectID: "GCLOUD_PROJECT_ID"
  location: "GCLOUD_SERVER_LOCATION"
  modelID: "GCLOUD_AUTOML_MODEL_ID"



