database:
  connectionUri: "asdasdmongodb://127.0.0.1:27017"

server:
  port: 8080

staticfile:
  dir: "/mnt"
  maxUploadSize: 4096

gcloud:
  projectID: "ecommercechatbotdev-wcscos"
  location: "us-central1"
  modelID: "ICN7880492306363580416"
  filePath: ""

